[features]
seeds = false
[programs.devnet]
tokens = "53pUyMnFNBEbpncA5sKZHjmf2bexs2Rk7s7d8no4vVd8"

[programs.localnet]
tokens = "53pUyMnFNBEbpncA5sKZHjmf2bexs2Rk7s7d8no4vVd8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
